# NOTE: iac/install_terraform.yml

terraform_version: 1.14.3-1 # NOTE: run `apt-cache madison terraform` to see how apt resolves the terraform version
#terraform_version: latest  # NOTE: latest version can be installed if required

# NOTE: iac/install_gh_actions.yml

runner_version: "latest"   # or pin e.g. "2.317.0"
runner_dir: "/opt/actions-runner"
runner_user: "github"
runner_labels: "self-hosted,ubuntu"
