# NOTE: ansible_setup | systemd.yml
ansible_repo_url: https://github.com/rtdevx/cicd-ansible-pull


#NOTE: users | robk.yml (Password sha512 hash)
robk_passwd: "7341246b384c196f88fef641bf1bc794171e006e033d870aa2fce80f3c10617e80957b26cb300ac0c5d63206743676e847e879024a0b96c6f10131f638c0bf97"
