# NOTE: Install terraform

- name: iac | install_terraform.yml | Install required packages for terraform
  tags: packages,system,settings
  package:
    state: latest
    name:
      - gnupg
      - software-properties-common
      - apt-transport-https
      - ca-certificates     

- name: iac | install_terraform.yml | Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: iac | install_terraform.yml | Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: iac | install_terraform.yml | Install Terraform {{ terraform_version }}
  package:
    name: terraform={{ terraform_version }}
    state: present
    allow_downgrade: true
  when: ansible_distribution in ["Debian", "Ubuntu"]