# NOTE: Install terraform

- name: servers_iac | install required packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - gnupg
      - software-properties-common
      - apt-transport-https
      - ca-certificates     

- name: servers_iac | Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: servers_iac | Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: servers_iac | Install Terraform
  package:
    name: terraform="1.14.3"
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]

# NOTE: Install GitHub self-hosted runner

